apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
  - ../base
resources:
  - ../../../admission-webhook/webhook/v3
  - ../../../common/centraldashboard/overlays/stacks
  - ../../application/bootstrap
  - ../../../kubeflow-roles/base
  - ../../application/profiles
configMapGenerator:
- name: profiles-config
  behavior: merge
  literals:
  - admin=example@kubeflow.org
