apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer
spec:
  template:
    spec:
      containers:
      - name: main
        env:
        - name: ENABLE_ARCHIVE_LOGS
          valueFrom:
            configMapKeyRef:
              name: kfp-tekton-config
              key: enable_archive_logs
