apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeflow-pipelines-metadata-writer-role
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  - conditions
  verbs:
  - get
  - list
  - watch
  - update
  - patch
