apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ml-pipeline
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  - conditions
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
