apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ml-pipeline-persistenceagent-role
rules:
- apiGroups:
  - tekton.dev
  resources:
  - pipelineruns
  - taskruns
  - conditions
  verbs:
  - get
  - list
  - watch
