apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
  - ../base
resources:
  - ../../../pytorch-job/pytorch-job-crds/overlays/application
  - ../../../pytorch-job/pytorch-operator/overlays/application
